// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddScrapItemRequest add scrap item request
//
// swagger:model AddScrapItemRequest
type AddScrapItemRequest struct {

	// Consumption should not be recorded for this scrap request
	IgnoreConsumption bool `json:"IgnoreConsumption,omitempty"`

	// location Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	LocationID strfmt.UUID `json:"LocationId,omitempty"`

	// scrap item
	ScrapItem *ScrapItem `json:"ScrapItem,omitempty"`
}

// Validate validates this add scrap item request
func (m *AddScrapItemRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScrapItem(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddScrapItemRequest) validateLocationID(formats strfmt.Registry) error {
	if swag.IsZero(m.LocationID) { // not required
		return nil
	}

	if err := validate.FormatOf("LocationId", "body", "uuid", m.LocationID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AddScrapItemRequest) validateScrapItem(formats strfmt.Registry) error {
	if swag.IsZero(m.ScrapItem) { // not required
		return nil
	}

	if m.ScrapItem != nil {
		if err := m.ScrapItem.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ScrapItem")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ScrapItem")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this add scrap item request based on the context it is used
func (m *AddScrapItemRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateScrapItem(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddScrapItemRequest) contextValidateScrapItem(ctx context.Context, formats strfmt.Registry) error {

	if m.ScrapItem != nil {

		if swag.IsZero(m.ScrapItem) { // not required
			return nil
		}

		if err := m.ScrapItem.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ScrapItem")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ScrapItem")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AddScrapItemRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddScrapItemRequest) UnmarshalBinary(b []byte) error {
	var res AddScrapItemRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
