// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddInventoryItemRequest add inventory item request
//
// swagger:model AddInventoryItemRequest
type AddInventoryItemRequest struct {

	// inventory items
	InventoryItems []*StockItemHeader `json:"InventoryItems"`
}

// Validate validates this add inventory item request
func (m *AddInventoryItemRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInventoryItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddInventoryItemRequest) validateInventoryItems(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItems) { // not required
		return nil
	}

	for i := 0; i < len(m.InventoryItems); i++ {
		if swag.IsZero(m.InventoryItems[i]) { // not required
			continue
		}

		if m.InventoryItems[i] != nil {
			if err := m.InventoryItems[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("InventoryItems" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("InventoryItems" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this add inventory item request based on the context it is used
func (m *AddInventoryItemRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInventoryItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddInventoryItemRequest) contextValidateInventoryItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InventoryItems); i++ {

		if m.InventoryItems[i] != nil {

			if swag.IsZero(m.InventoryItems[i]) { // not required
				return nil
			}

			if err := m.InventoryItems[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("InventoryItems" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("InventoryItems" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AddInventoryItemRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddInventoryItemRequest) UnmarshalBinary(b []byte) error {
	var res AddInventoryItemRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
