// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConfigPostalServiceMappingItem config postal service mapping item
//
// swagger:model ConfigPostalServiceMappingItem
type ConfigPostalServiceMappingItem struct {

	// is changed
	// Read Only: true
	IsChanged *bool `json:"IsChanged,omitempty"`

	// postal service name
	PostalServiceName string `json:"PostalServiceName,omitempty"`

	// site
	Site string `json:"Site,omitempty"`

	// tag
	Tag string `json:"Tag,omitempty"`

	// fk channel Id
	FkChannelID int32 `json:"fkChannelId,omitempty"`

	// fk postal service Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	FkPostalServiceID strfmt.UUID `json:"fkPostalServiceId,omitempty"`

	// pk row Id
	PkRowID int32 `json:"pkRowId,omitempty"`
}

// Validate validates this config postal service mapping item
func (m *ConfigPostalServiceMappingItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFkPostalServiceID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigPostalServiceMappingItem) validateFkPostalServiceID(formats strfmt.Registry) error {
	if swag.IsZero(m.FkPostalServiceID) { // not required
		return nil
	}

	if err := validate.FormatOf("fkPostalServiceId", "body", "uuid", m.FkPostalServiceID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this config postal service mapping item based on the context it is used
func (m *ConfigPostalServiceMappingItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIsChanged(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigPostalServiceMappingItem) contextValidateIsChanged(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "IsChanged", "body", m.IsChanged); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigPostalServiceMappingItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigPostalServiceMappingItem) UnmarshalBinary(b []byte) error {
	var res ConfigPostalServiceMappingItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
