// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CustomAttributeTypedArgument custom attribute typed argument
//
// swagger:model CustomAttributeTypedArgument
type CustomAttributeTypedArgument struct {

	// argument type
	// Read Only: true
	ArgumentType string `json:"ArgumentType,omitempty"`

	// value
	// Read Only: true
	Value any `json:"Value,omitempty"`
}

// Validate validates this custom attribute typed argument
func (m *CustomAttributeTypedArgument) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this custom attribute typed argument based on the context it is used
func (m *CustomAttributeTypedArgument) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArgumentType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustomAttributeTypedArgument) contextValidateArgumentType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "ArgumentType", "body", m.ArgumentType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CustomAttributeTypedArgument) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomAttributeTypedArgument) UnmarshalBinary(b []byte) error {
	var res CustomAttributeTypedArgument
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
