// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteProductIdentifiersRequest delete product identifiers request
//
// swagger:model DeleteProductIdentifiersRequest
type DeleteProductIdentifiersRequest struct {

	// product identifier ids
	ProductIdentifierIds []int64 `json:"ProductIdentifierIds"`
}

// Validate validates this delete product identifiers request
func (m *DeleteProductIdentifiersRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete product identifiers request based on context it is used
func (m *DeleteProductIdentifiersRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteProductIdentifiersRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteProductIdentifiersRequest) UnmarshalBinary(b []byte) error {
	var res DeleteProductIdentifiersRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
