// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteScrapCategoriesRequest delete scrap categories request
//
// swagger:model DeleteScrapCategoriesRequest
type DeleteScrapCategoriesRequest struct {

	// category ids
	CategoryIds []int32 `json:"CategoryIds"`
}

// Validate validates this delete scrap categories request
func (m *DeleteScrapCategoriesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete scrap categories request based on context it is used
func (m *DeleteScrapCategoriesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteScrapCategoriesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteScrapCategoriesRequest) UnmarshalBinary(b []byte) error {
	var res DeleteScrapCategoriesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
