// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetScrapHistoryRequest get scrap history request
//
// swagger:model GetScrapHistoryRequest
type GetScrapHistoryRequest struct {

	// entries per page
	EntriesPerPage int32 `json:"EntriesPerPage,omitempty"`

	// page number
	PageNumber int32 `json:"PageNumber,omitempty"`
}

// Validate validates this get scrap history request
func (m *GetScrapHistoryRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get scrap history request based on context it is used
func (m *GetScrapHistoryRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetScrapHistoryRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetScrapHistoryRequest) UnmarshalBinary(b []byte) error {
	var res GetScrapHistoryRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
