// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetProductIdentifiersByStockItemIDRequest get product identifiers by stock item Id request
//
// swagger:model GetProductIdentifiersByStockItemIdRequest
type GetProductIdentifiersByStockItemIDRequest struct {

	// stock item Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	StockItemID strfmt.UUID `json:"StockItemId,omitempty"`
}

// Validate validates this get product identifiers by stock item Id request
func (m *GetProductIdentifiersByStockItemIDRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStockItemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetProductIdentifiersByStockItemIDRequest) validateStockItemID(formats strfmt.Registry) error {
	if swag.IsZero(m.StockItemID) { // not required
		return nil
	}

	if err := validate.FormatOf("StockItemId", "body", "uuid", m.StockItemID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get product identifiers by stock item Id request based on context it is used
func (m *GetProductIdentifiersByStockItemIDRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetProductIdentifiersByStockItemIDRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetProductIdentifiersByStockItemIDRequest) UnmarshalBinary(b []byte) error {
	var res GetProductIdentifiersByStockItemIDRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
