// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetProductIdentifiersBulkByStockItemIDRequest get product identifiers bulk by stock item Id request
//
// swagger:model GetProductIdentifiersBulkByStockItemIdRequest
type GetProductIdentifiersBulkByStockItemIDRequest struct {

	// stock item ids
	StockItemIds []strfmt.UUID `json:"StockItemIds"`
}

// Validate validates this get product identifiers bulk by stock item Id request
func (m *GetProductIdentifiersBulkByStockItemIDRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStockItemIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetProductIdentifiersBulkByStockItemIDRequest) validateStockItemIds(formats strfmt.Registry) error {
	if swag.IsZero(m.StockItemIds) { // not required
		return nil
	}

	for i := 0; i < len(m.StockItemIds); i++ {

		if err := validate.FormatOf("StockItemIds"+"."+strconv.Itoa(i), "body", "uuid", m.StockItemIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this get product identifiers bulk by stock item Id request based on context it is used
func (m *GetProductIdentifiersBulkByStockItemIDRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetProductIdentifiersBulkByStockItemIDRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetProductIdentifiersBulkByStockItemIDRequest) UnmarshalBinary(b []byte) error {
	var res GetProductIdentifiersBulkByStockItemIDRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
