// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetScrapCategoriesResponse get scrap categories response
//
// swagger:model GetScrapCategoriesResponse
type GetScrapCategoriesResponse struct {

	// scrap categories
	ScrapCategories []*ScrapCategory `json:"ScrapCategories"`
}

// Validate validates this get scrap categories response
func (m *GetScrapCategoriesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateScrapCategories(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetScrapCategoriesResponse) validateScrapCategories(formats strfmt.Registry) error {
	if swag.IsZero(m.ScrapCategories) { // not required
		return nil
	}

	for i := 0; i < len(m.ScrapCategories); i++ {
		if swag.IsZero(m.ScrapCategories[i]) { // not required
			continue
		}

		if m.ScrapCategories[i] != nil {
			if err := m.ScrapCategories[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("ScrapCategories" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("ScrapCategories" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get scrap categories response based on the context it is used
func (m *GetScrapCategoriesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateScrapCategories(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetScrapCategoriesResponse) contextValidateScrapCategories(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ScrapCategories); i++ {

		if m.ScrapCategories[i] != nil {

			if swag.IsZero(m.ScrapCategories[i]) { // not required
				return nil
			}

			if err := m.ScrapCategories[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("ScrapCategories" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("ScrapCategories" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetScrapCategoriesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetScrapCategoriesResponse) UnmarshalBinary(b []byte) error {
	var res GetScrapCategoriesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
