// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetInventoryItemRequest get inventory item request
//
// swagger:model GetInventoryItemRequest
type GetInventoryItemRequest struct {

	// The SKU for the item.
	// Only used when StockItemId is not supplied
	SKU string `json:"SKU,omitempty"`

	// The Linnworks stock item id.
	// Used in preference over SKU when supplied
	// If not supplied, the SKU will be used
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	StockItemID strfmt.UUID `json:"StockItemId,omitempty"`
}

// Validate validates this get inventory item request
func (m *GetInventoryItemRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStockItemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetInventoryItemRequest) validateStockItemID(formats strfmt.Registry) error {
	if swag.IsZero(m.StockItemID) { // not required
		return nil
	}

	if err := validate.FormatOf("StockItemId", "body", "uuid", m.StockItemID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get inventory item request based on context it is used
func (m *GetInventoryItemRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetInventoryItemRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetInventoryItemRequest) UnmarshalBinary(b []byte) error {
	var res GetInventoryItemRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
