// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryDeleteInventoryItemPricesRequest inventory delete inventory item prices request
//
// swagger:model Inventory_DeleteInventoryItemPricesRequest
type InventoryDeleteInventoryItemPricesRequest struct {

	// List of stock item prices
	InventoryItemPriceIds []strfmt.UUID `json:"inventoryItemPriceIds"`
}

// Validate validates this inventory delete inventory item prices request
func (m *InventoryDeleteInventoryItemPricesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInventoryItemPriceIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryDeleteInventoryItemPricesRequest) validateInventoryItemPriceIds(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItemPriceIds) { // not required
		return nil
	}

	for i := 0; i < len(m.InventoryItemPriceIds); i++ {

		if err := validate.FormatOf("inventoryItemPriceIds"+"."+strconv.Itoa(i), "body", "uuid", m.InventoryItemPriceIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this inventory delete inventory item prices request based on context it is used
func (m *InventoryDeleteInventoryItemPricesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemPricesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemPricesRequest) UnmarshalBinary(b []byte) error {
	var res InventoryDeleteInventoryItemPricesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
