// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryCreateInventoryItemCompositionsRequest inventory create inventory item compositions request
//
// swagger:model Inventory_CreateInventoryItemCompositionsRequest
type InventoryCreateInventoryItemCompositionsRequest struct {

	// stockItem compositions
	InventoryItemCompositions []*StockItemComposition `json:"inventoryItemCompositions"`
}

// Validate validates this inventory create inventory item compositions request
func (m *InventoryCreateInventoryItemCompositionsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInventoryItemCompositions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryCreateInventoryItemCompositionsRequest) validateInventoryItemCompositions(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItemCompositions) { // not required
		return nil
	}

	for i := 0; i < len(m.InventoryItemCompositions); i++ {
		if swag.IsZero(m.InventoryItemCompositions[i]) { // not required
			continue
		}

		if m.InventoryItemCompositions[i] != nil {
			if err := m.InventoryItemCompositions[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("inventoryItemCompositions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("inventoryItemCompositions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inventory create inventory item compositions request based on the context it is used
func (m *InventoryCreateInventoryItemCompositionsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInventoryItemCompositions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryCreateInventoryItemCompositionsRequest) contextValidateInventoryItemCompositions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InventoryItemCompositions); i++ {

		if m.InventoryItemCompositions[i] != nil {

			if swag.IsZero(m.InventoryItemCompositions[i]) { // not required
				return nil
			}

			if err := m.InventoryItemCompositions[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("inventoryItemCompositions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("inventoryItemCompositions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryCreateInventoryItemCompositionsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryCreateInventoryItemCompositionsRequest) UnmarshalBinary(b []byte) error {
	var res InventoryCreateInventoryItemCompositionsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
