// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryDeleteCategoryByIDRequest inventory delete category by Id request
//
// swagger:model Inventory_DeleteCategoryByIdRequest
type InventoryDeleteCategoryByIDRequest struct {

	// Unique id that identifies the category that you want to delete.
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	CategoryID strfmt.UUID `json:"categoryId,omitempty"`
}

// Validate validates this inventory delete category by Id request
func (m *InventoryDeleteCategoryByIDRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategoryID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryDeleteCategoryByIDRequest) validateCategoryID(formats strfmt.Registry) error {
	if swag.IsZero(m.CategoryID) { // not required
		return nil
	}

	if err := validate.FormatOf("categoryId", "body", "uuid", m.CategoryID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this inventory delete category by Id request based on context it is used
func (m *InventoryDeleteCategoryByIDRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryDeleteCategoryByIDRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryDeleteCategoryByIDRequest) UnmarshalBinary(b []byte) error {
	var res InventoryDeleteCategoryByIDRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
