// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryUpdateStockSupplierStatRequest inventory update stock supplier stat request
//
// swagger:model Inventory_UpdateStockSupplierStatRequest
type InventoryUpdateStockSupplierStatRequest struct {

	// List of StockItemSupplierStat
	ItemSuppliers []*StockItemSupplierStat `json:"itemSuppliers"`
}

// Validate validates this inventory update stock supplier stat request
func (m *InventoryUpdateStockSupplierStatRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItemSuppliers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryUpdateStockSupplierStatRequest) validateItemSuppliers(formats strfmt.Registry) error {
	if swag.IsZero(m.ItemSuppliers) { // not required
		return nil
	}

	for i := 0; i < len(m.ItemSuppliers); i++ {
		if swag.IsZero(m.ItemSuppliers[i]) { // not required
			continue
		}

		if m.ItemSuppliers[i] != nil {
			if err := m.ItemSuppliers[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("itemSuppliers" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("itemSuppliers" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inventory update stock supplier stat request based on the context it is used
func (m *InventoryUpdateStockSupplierStatRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateItemSuppliers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryUpdateStockSupplierStatRequest) contextValidateItemSuppliers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ItemSuppliers); i++ {

		if m.ItemSuppliers[i] != nil {

			if swag.IsZero(m.ItemSuppliers[i]) { // not required
				return nil
			}

			if err := m.ItemSuppliers[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("itemSuppliers" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("itemSuppliers" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryUpdateStockSupplierStatRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryUpdateStockSupplierStatRequest) UnmarshalBinary(b []byte) error {
	var res InventoryUpdateStockSupplierStatRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
