// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryGetStockItemLabelsRequest inventory get stock item labels request
//
// swagger:model Inventory_GetStockItemLabelsRequest
type InventoryGetStockItemLabelsRequest struct {

	// Location id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	Location strfmt.UUID `json:"location,omitempty"`

	// Row numbers to retrieve item ids for
	SelectedRegions []*TupleInt32Int32 `json:"selectedRegions"`

	// Search Token
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	Token strfmt.UUID `json:"token,omitempty"`
}

// Validate validates this inventory get stock item labels request
func (m *InventoryGetStockItemLabelsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelectedRegions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryGetStockItemLabelsRequest) validateLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.Location) { // not required
		return nil
	}

	if err := validate.FormatOf("location", "body", "uuid", m.Location.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *InventoryGetStockItemLabelsRequest) validateSelectedRegions(formats strfmt.Registry) error {
	if swag.IsZero(m.SelectedRegions) { // not required
		return nil
	}

	for i := 0; i < len(m.SelectedRegions); i++ {
		if swag.IsZero(m.SelectedRegions[i]) { // not required
			continue
		}

		if m.SelectedRegions[i] != nil {
			if err := m.SelectedRegions[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("selectedRegions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("selectedRegions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *InventoryGetStockItemLabelsRequest) validateToken(formats strfmt.Registry) error {
	if swag.IsZero(m.Token) { // not required
		return nil
	}

	if err := validate.FormatOf("token", "body", "uuid", m.Token.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this inventory get stock item labels request based on the context it is used
func (m *InventoryGetStockItemLabelsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSelectedRegions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryGetStockItemLabelsRequest) contextValidateSelectedRegions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SelectedRegions); i++ {

		if m.SelectedRegions[i] != nil {

			if swag.IsZero(m.SelectedRegions[i]) { // not required
				return nil
			}

			if err := m.SelectedRegions[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("selectedRegions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("selectedRegions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryGetStockItemLabelsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryGetStockItemLabelsRequest) UnmarshalBinary(b []byte) error {
	var res InventoryGetStockItemLabelsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
