// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryGetInventoryItemAuditTrailPagedRequest inventory get inventory item audit trail paged request
//
// swagger:model Inventory_GetInventoryItemAuditTrailPagedRequest
type InventoryGetInventoryItemAuditTrailPagedRequest struct {

	// Set of filter options
	Request *GetInventoryItemAuditTrailPagedRequest `json:"request,omitempty"`
}

// Validate validates this inventory get inventory item audit trail paged request
func (m *InventoryGetInventoryItemAuditTrailPagedRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryGetInventoryItemAuditTrailPagedRequest) validateRequest(formats strfmt.Registry) error {
	if swag.IsZero(m.Request) { // not required
		return nil
	}

	if m.Request != nil {
		if err := m.Request.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("request")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("request")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this inventory get inventory item audit trail paged request based on the context it is used
func (m *InventoryGetInventoryItemAuditTrailPagedRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryGetInventoryItemAuditTrailPagedRequest) contextValidateRequest(ctx context.Context, formats strfmt.Registry) error {

	if m.Request != nil {

		if swag.IsZero(m.Request) { // not required
			return nil
		}

		if err := m.Request.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("request")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("request")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryGetInventoryItemAuditTrailPagedRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryGetInventoryItemAuditTrailPagedRequest) UnmarshalBinary(b []byte) error {
	var res InventoryGetInventoryItemAuditTrailPagedRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
