// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryDeleteImagesFromInventoryItemRequest inventory delete images from inventory item request
//
// swagger:model Inventory_DeleteImagesFromInventoryItemRequest
type InventoryDeleteImagesFromInventoryItemRequest struct {

	// Inventory item ids and a list of image urls to be deleted for each item
	InventoryItemImages map[string][]string `json:"inventoryItemImages,omitempty"`
}

// Validate validates this inventory delete images from inventory item request
func (m *InventoryDeleteImagesFromInventoryItemRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this inventory delete images from inventory item request based on context it is used
func (m *InventoryDeleteImagesFromInventoryItemRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryDeleteImagesFromInventoryItemRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryDeleteImagesFromInventoryItemRequest) UnmarshalBinary(b []byte) error {
	var res InventoryDeleteImagesFromInventoryItemRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
