// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryUpdateInventoryItemLevelsRequest inventory update inventory item levels request
//
// swagger:model Inventory_UpdateInventoryItemLevelsRequest
type InventoryUpdateInventoryItemLevelsRequest struct {

	// change source
	ChangeSource string `json:"changeSource,omitempty"`

	// Name of field updated
	// Enum: ["SKU","Title","VariationGroupName","RetailPrice","PurchasePrice","Tracked","Barcode","Available","MinimumLevel","InOrder","StockLevel","StockValue","Due","BinRack","Category","Image","Weight","DimHeight","DimWidth","DimDepth","CreatedDate","ModifiedDate","SerialNumberScanRequired","BatchNumberScanRequired","BatchType","JIT","ReorderAmount","ReorderDate","AverageConsumption","DefaultSupplier"]
	FieldName string `json:"fieldName,omitempty"`

	// Input value
	FieldValue string `json:"fieldValue,omitempty"`

	// Stock Item Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	InventoryItemID strfmt.UUID `json:"inventoryItemId,omitempty"`

	// Location Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	LocationID strfmt.UUID `json:"locationId,omitempty"`
}

// Validate validates this inventory update inventory item levels request
func (m *InventoryUpdateInventoryItemLevelsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInventoryItemID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocationID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var inventoryUpdateInventoryItemLevelsRequestTypeFieldNamePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SKU","Title","VariationGroupName","RetailPrice","PurchasePrice","Tracked","Barcode","Available","MinimumLevel","InOrder","StockLevel","StockValue","Due","BinRack","Category","Image","Weight","DimHeight","DimWidth","DimDepth","CreatedDate","ModifiedDate","SerialNumberScanRequired","BatchNumberScanRequired","BatchType","JIT","ReorderAmount","ReorderDate","AverageConsumption","DefaultSupplier"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		inventoryUpdateInventoryItemLevelsRequestTypeFieldNamePropEnum = append(inventoryUpdateInventoryItemLevelsRequestTypeFieldNamePropEnum, v)
	}
}

const (

	// InventoryUpdateInventoryItemLevelsRequestFieldNameSKU captures enum value "SKU"
	InventoryUpdateInventoryItemLevelsRequestFieldNameSKU string = "SKU"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameTitle captures enum value "Title"
	InventoryUpdateInventoryItemLevelsRequestFieldNameTitle string = "Title"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameVariationGroupName captures enum value "VariationGroupName"
	InventoryUpdateInventoryItemLevelsRequestFieldNameVariationGroupName string = "VariationGroupName"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameRetailPrice captures enum value "RetailPrice"
	InventoryUpdateInventoryItemLevelsRequestFieldNameRetailPrice string = "RetailPrice"

	// InventoryUpdateInventoryItemLevelsRequestFieldNamePurchasePrice captures enum value "PurchasePrice"
	InventoryUpdateInventoryItemLevelsRequestFieldNamePurchasePrice string = "PurchasePrice"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameTracked captures enum value "Tracked"
	InventoryUpdateInventoryItemLevelsRequestFieldNameTracked string = "Tracked"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameBarcode captures enum value "Barcode"
	InventoryUpdateInventoryItemLevelsRequestFieldNameBarcode string = "Barcode"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameAvailable captures enum value "Available"
	InventoryUpdateInventoryItemLevelsRequestFieldNameAvailable string = "Available"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameMinimumLevel captures enum value "MinimumLevel"
	InventoryUpdateInventoryItemLevelsRequestFieldNameMinimumLevel string = "MinimumLevel"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameInOrder captures enum value "InOrder"
	InventoryUpdateInventoryItemLevelsRequestFieldNameInOrder string = "InOrder"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameStockLevel captures enum value "StockLevel"
	InventoryUpdateInventoryItemLevelsRequestFieldNameStockLevel string = "StockLevel"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameStockValue captures enum value "StockValue"
	InventoryUpdateInventoryItemLevelsRequestFieldNameStockValue string = "StockValue"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameDue captures enum value "Due"
	InventoryUpdateInventoryItemLevelsRequestFieldNameDue string = "Due"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameBinRack captures enum value "BinRack"
	InventoryUpdateInventoryItemLevelsRequestFieldNameBinRack string = "BinRack"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameCategory captures enum value "Category"
	InventoryUpdateInventoryItemLevelsRequestFieldNameCategory string = "Category"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameImage captures enum value "Image"
	InventoryUpdateInventoryItemLevelsRequestFieldNameImage string = "Image"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameWeight captures enum value "Weight"
	InventoryUpdateInventoryItemLevelsRequestFieldNameWeight string = "Weight"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameDimHeight captures enum value "DimHeight"
	InventoryUpdateInventoryItemLevelsRequestFieldNameDimHeight string = "DimHeight"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameDimWidth captures enum value "DimWidth"
	InventoryUpdateInventoryItemLevelsRequestFieldNameDimWidth string = "DimWidth"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameDimDepth captures enum value "DimDepth"
	InventoryUpdateInventoryItemLevelsRequestFieldNameDimDepth string = "DimDepth"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameCreatedDate captures enum value "CreatedDate"
	InventoryUpdateInventoryItemLevelsRequestFieldNameCreatedDate string = "CreatedDate"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameModifiedDate captures enum value "ModifiedDate"
	InventoryUpdateInventoryItemLevelsRequestFieldNameModifiedDate string = "ModifiedDate"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameSerialNumberScanRequired captures enum value "SerialNumberScanRequired"
	InventoryUpdateInventoryItemLevelsRequestFieldNameSerialNumberScanRequired string = "SerialNumberScanRequired"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameBatchNumberScanRequired captures enum value "BatchNumberScanRequired"
	InventoryUpdateInventoryItemLevelsRequestFieldNameBatchNumberScanRequired string = "BatchNumberScanRequired"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameBatchType captures enum value "BatchType"
	InventoryUpdateInventoryItemLevelsRequestFieldNameBatchType string = "BatchType"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameJIT captures enum value "JIT"
	InventoryUpdateInventoryItemLevelsRequestFieldNameJIT string = "JIT"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameReorderAmount captures enum value "ReorderAmount"
	InventoryUpdateInventoryItemLevelsRequestFieldNameReorderAmount string = "ReorderAmount"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameReorderDate captures enum value "ReorderDate"
	InventoryUpdateInventoryItemLevelsRequestFieldNameReorderDate string = "ReorderDate"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameAverageConsumption captures enum value "AverageConsumption"
	InventoryUpdateInventoryItemLevelsRequestFieldNameAverageConsumption string = "AverageConsumption"

	// InventoryUpdateInventoryItemLevelsRequestFieldNameDefaultSupplier captures enum value "DefaultSupplier"
	InventoryUpdateInventoryItemLevelsRequestFieldNameDefaultSupplier string = "DefaultSupplier"
)

// prop value enum
func (m *InventoryUpdateInventoryItemLevelsRequest) validateFieldNameEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, inventoryUpdateInventoryItemLevelsRequestTypeFieldNamePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *InventoryUpdateInventoryItemLevelsRequest) validateFieldName(formats strfmt.Registry) error {
	if swag.IsZero(m.FieldName) { // not required
		return nil
	}

	// value enum
	if err := m.validateFieldNameEnum("fieldName", "body", m.FieldName); err != nil {
		return err
	}

	return nil
}

func (m *InventoryUpdateInventoryItemLevelsRequest) validateInventoryItemID(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItemID) { // not required
		return nil
	}

	if err := validate.FormatOf("inventoryItemId", "body", "uuid", m.InventoryItemID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *InventoryUpdateInventoryItemLevelsRequest) validateLocationID(formats strfmt.Registry) error {
	if swag.IsZero(m.LocationID) { // not required
		return nil
	}

	if err := validate.FormatOf("locationId", "body", "uuid", m.LocationID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this inventory update inventory item levels request based on context it is used
func (m *InventoryUpdateInventoryItemLevelsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryUpdateInventoryItemLevelsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryUpdateInventoryItemLevelsRequest) UnmarshalBinary(b []byte) error {
	var res InventoryUpdateInventoryItemLevelsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
