// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryUpdateInventoryItemPricesRequest inventory update inventory item prices request
//
// swagger:model Inventory_UpdateInventoryItemPricesRequest
type InventoryUpdateInventoryItemPricesRequest struct {

	// List of stock item prices to update
	InventoryItemPrices []*StockItemPrice `json:"inventoryItemPrices"`
}

// Validate validates this inventory update inventory item prices request
func (m *InventoryUpdateInventoryItemPricesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInventoryItemPrices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryUpdateInventoryItemPricesRequest) validateInventoryItemPrices(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItemPrices) { // not required
		return nil
	}

	for i := 0; i < len(m.InventoryItemPrices); i++ {
		if swag.IsZero(m.InventoryItemPrices[i]) { // not required
			continue
		}

		if m.InventoryItemPrices[i] != nil {
			if err := m.InventoryItemPrices[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("inventoryItemPrices" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("inventoryItemPrices" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inventory update inventory item prices request based on the context it is used
func (m *InventoryUpdateInventoryItemPricesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInventoryItemPrices(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryUpdateInventoryItemPricesRequest) contextValidateInventoryItemPrices(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InventoryItemPrices); i++ {

		if m.InventoryItemPrices[i] != nil {

			if swag.IsZero(m.InventoryItemPrices[i]) { // not required
				return nil
			}

			if err := m.InventoryItemPrices[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("inventoryItemPrices" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("inventoryItemPrices" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryUpdateInventoryItemPricesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryUpdateInventoryItemPricesRequest) UnmarshalBinary(b []byte) error {
	var res InventoryUpdateInventoryItemPricesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
