// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryUpdateInventoryItemTitlesRequest inventory update inventory item titles request
//
// swagger:model Inventory_UpdateInventoryItemTitlesRequest
type InventoryUpdateInventoryItemTitlesRequest struct {

	// list of stockitem Titles
	InventoryItemTitles []*StockItemTitle `json:"inventoryItemTitles"`
}

// Validate validates this inventory update inventory item titles request
func (m *InventoryUpdateInventoryItemTitlesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInventoryItemTitles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryUpdateInventoryItemTitlesRequest) validateInventoryItemTitles(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItemTitles) { // not required
		return nil
	}

	for i := 0; i < len(m.InventoryItemTitles); i++ {
		if swag.IsZero(m.InventoryItemTitles[i]) { // not required
			continue
		}

		if m.InventoryItemTitles[i] != nil {
			if err := m.InventoryItemTitles[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("inventoryItemTitles" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("inventoryItemTitles" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inventory update inventory item titles request based on the context it is used
func (m *InventoryUpdateInventoryItemTitlesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInventoryItemTitles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryUpdateInventoryItemTitlesRequest) contextValidateInventoryItemTitles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InventoryItemTitles); i++ {

		if m.InventoryItemTitles[i] != nil {

			if swag.IsZero(m.InventoryItemTitles[i]) { // not required
				return nil
			}

			if err := m.InventoryItemTitles[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("inventoryItemTitles" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("inventoryItemTitles" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryUpdateInventoryItemTitlesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryUpdateInventoryItemTitlesRequest) UnmarshalBinary(b []byte) error {
	var res InventoryUpdateInventoryItemTitlesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
