// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryAddSupplierRequest inventory add supplier request
//
// swagger:model Inventory_AddSupplierRequest
type InventoryAddSupplierRequest struct {

	// Details of supplier to be added. Set pkSupplierId to a new uniqueidentifier
	Supplier *Supplier `json:"supplier,omitempty"`
}

// Validate validates this inventory add supplier request
func (m *InventoryAddSupplierRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSupplier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryAddSupplierRequest) validateSupplier(formats strfmt.Registry) error {
	if swag.IsZero(m.Supplier) { // not required
		return nil
	}

	if m.Supplier != nil {
		if err := m.Supplier.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("supplier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("supplier")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this inventory add supplier request based on the context it is used
func (m *InventoryAddSupplierRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSupplier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryAddSupplierRequest) contextValidateSupplier(ctx context.Context, formats strfmt.Registry) error {

	if m.Supplier != nil {

		if swag.IsZero(m.Supplier) { // not required
			return nil
		}

		if err := m.Supplier.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("supplier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("supplier")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryAddSupplierRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryAddSupplierRequest) UnmarshalBinary(b []byte) error {
	var res InventoryAddSupplierRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
