// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryBatchGetInventoryItemChannelSKUsRequest inventory batch get inventory item channel s k us request
//
// swagger:model Inventory_BatchGetInventoryItemChannelSKUsRequest
type InventoryBatchGetInventoryItemChannelSKUsRequest struct {

	// List of Stock item Id's'
	InventoryItemIds []strfmt.UUID `json:"inventoryItemIds"`
}

// Validate validates this inventory batch get inventory item channel s k us request
func (m *InventoryBatchGetInventoryItemChannelSKUsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInventoryItemIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryBatchGetInventoryItemChannelSKUsRequest) validateInventoryItemIds(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItemIds) { // not required
		return nil
	}

	for i := 0; i < len(m.InventoryItemIds); i++ {

		if err := validate.FormatOf("inventoryItemIds"+"."+strconv.Itoa(i), "body", "uuid", m.InventoryItemIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this inventory batch get inventory item channel s k us request based on context it is used
func (m *InventoryBatchGetInventoryItemChannelSKUsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryBatchGetInventoryItemChannelSKUsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryBatchGetInventoryItemChannelSKUsRequest) UnmarshalBinary(b []byte) error {
	var res InventoryBatchGetInventoryItemChannelSKUsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
