// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryDeleteInventoryItemsRequest inventory delete inventory items request
//
// swagger:model Inventory_DeleteInventoryItemsRequest
type InventoryDeleteInventoryItemsRequest struct {

	// List of stock item IDs that needs to be deleted
	InventoryItemIds []strfmt.UUID `json:"inventoryItemIds"`

	// Do not send this parameter
	Request *DeleteInventoryItemsRequest `json:"request,omitempty"`
}

// Validate validates this inventory delete inventory items request
func (m *InventoryDeleteInventoryItemsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInventoryItemIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryDeleteInventoryItemsRequest) validateInventoryItemIds(formats strfmt.Registry) error {
	if swag.IsZero(m.InventoryItemIds) { // not required
		return nil
	}

	for i := 0; i < len(m.InventoryItemIds); i++ {

		if err := validate.FormatOf("inventoryItemIds"+"."+strconv.Itoa(i), "body", "uuid", m.InventoryItemIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

func (m *InventoryDeleteInventoryItemsRequest) validateRequest(formats strfmt.Registry) error {
	if swag.IsZero(m.Request) { // not required
		return nil
	}

	if m.Request != nil {
		if err := m.Request.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("request")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("request")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this inventory delete inventory items request based on the context it is used
func (m *InventoryDeleteInventoryItemsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryDeleteInventoryItemsRequest) contextValidateRequest(ctx context.Context, formats strfmt.Registry) error {

	if m.Request != nil {

		if swag.IsZero(m.Request) { // not required
			return nil
		}

		if err := m.Request.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("request")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("request")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemsRequest) UnmarshalBinary(b []byte) error {
	var res InventoryDeleteInventoryItemsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
