// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryDeleteInventoryItemImageBulkRequest inventory delete inventory item image bulk request
//
// swagger:model Inventory_DeleteInventoryItemImageBulkRequest
type InventoryDeleteInventoryItemImageBulkRequest struct {

	// request
	Request []*DeleteInventoryItemImagesRequest `json:"request"`
}

// Validate validates this inventory delete inventory item image bulk request
func (m *InventoryDeleteInventoryItemImageBulkRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryDeleteInventoryItemImageBulkRequest) validateRequest(formats strfmt.Registry) error {
	if swag.IsZero(m.Request) { // not required
		return nil
	}

	for i := 0; i < len(m.Request); i++ {
		if swag.IsZero(m.Request[i]) { // not required
			continue
		}

		if m.Request[i] != nil {
			if err := m.Request[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("request" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("request" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inventory delete inventory item image bulk request based on the context it is used
func (m *InventoryDeleteInventoryItemImageBulkRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryDeleteInventoryItemImageBulkRequest) contextValidateRequest(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Request); i++ {

		if m.Request[i] != nil {

			if swag.IsZero(m.Request[i]) { // not required
				return nil
			}

			if err := m.Request[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("request" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("request" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemImageBulkRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemImageBulkRequest) UnmarshalBinary(b []byte) error {
	var res InventoryDeleteInventoryItemImageBulkRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
