// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryDeleteInventoryItemPricingRulesRequest inventory delete inventory item pricing rules request
//
// swagger:model Inventory_DeleteInventoryItemPricingRulesRequest
type InventoryDeleteInventoryItemPricingRulesRequest struct {

	// List of stock item pricing rule ids to delete
	PricingRuleIds []int32 `json:"pricingRuleIds"`
}

// Validate validates this inventory delete inventory item pricing rules request
func (m *InventoryDeleteInventoryItemPricingRulesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this inventory delete inventory item pricing rules request based on context it is used
func (m *InventoryDeleteInventoryItemPricingRulesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemPricingRulesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryDeleteInventoryItemPricingRulesRequest) UnmarshalBinary(b []byte) error {
	var res InventoryDeleteInventoryItemPricingRulesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
