// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ItemsHaveScannableIdentifiersResponse items have scannable identifiers response
//
// swagger:model ItemsHaveScannableIdentifiersResponse
type ItemsHaveScannableIdentifiersResponse struct {

	// item scannable identifier mapping
	ItemScannableIdentifierMapping map[string]bool `json:"ItemScannableIdentifierMapping,omitempty"`
}

// Validate validates this items have scannable identifiers response
func (m *ItemsHaveScannableIdentifiersResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this items have scannable identifiers response based on context it is used
func (m *ItemsHaveScannableIdentifiersResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ItemsHaveScannableIdentifiersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ItemsHaveScannableIdentifiersResponse) UnmarshalBinary(b []byte) error {
	var res ItemsHaveScannableIdentifiersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
