// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KeyGUIDValue key Guid value
//
// swagger:model KeyGuidValue
type KeyGUIDValue struct {

	// key
	Key string `json:"Key,omitempty"`

	// value
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	Value strfmt.UUID `json:"Value,omitempty"`
}

// Validate validates this key Guid value
func (m *KeyGUIDValue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeyGUIDValue) validateValue(formats strfmt.Registry) error {
	if swag.IsZero(m.Value) { // not required
		return nil
	}

	if err := validate.FormatOf("Value", "body", "uuid", m.Value.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this key Guid value based on context it is used
func (m *KeyGUIDValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KeyGUIDValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KeyGUIDValue) UnmarshalBinary(b []byte) error {
	var res KeyGUIDValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
