// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LinnworksCategory linnworks category
//
// swagger:model LinnworksCategory
type LinnworksCategory struct {

	// Category ID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	CategoryID strfmt.UUID `json:"CategoryId,omitempty"`

	// Category name
	CategoryName string `json:"CategoryName,omitempty"`

	// product category Id
	ProductCategoryID int32 `json:"ProductCategoryId,omitempty"`

	// Structure Category Id to which this product category is assigned to, nullable if not available
	StructureCategoryID int32 `json:"StructureCategoryId,omitempty"`
}

// Validate validates this linnworks category
func (m *LinnworksCategory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategoryID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LinnworksCategory) validateCategoryID(formats strfmt.Registry) error {
	if swag.IsZero(m.CategoryID) { // not required
		return nil
	}

	if err := validate.FormatOf("CategoryId", "body", "uuid", m.CategoryID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this linnworks category based on context it is used
func (m *LinnworksCategory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LinnworksCategory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LinnworksCategory) UnmarshalBinary(b []byte) error {
	var res LinnworksCategory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
