// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PictureSource picture source
//
// swagger:model PictureSource
type PictureSource struct {

	// is main
	IsMain bool `json:"IsMain,omitempty"`

	// picture Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	PictureID strfmt.UUID `json:"PictureId,omitempty"`

	// sort order
	SortOrder int32 `json:"SortOrder,omitempty"`

	// source
	Source string `json:"Source,omitempty"`
}

// Validate validates this picture source
func (m *PictureSource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePictureID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PictureSource) validatePictureID(formats strfmt.Registry) error {
	if swag.IsZero(m.PictureID) { // not required
		return nil
	}

	if err := validate.FormatOf("PictureId", "body", "uuid", m.PictureID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this picture source based on context it is used
func (m *PictureSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PictureSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PictureSource) UnmarshalBinary(b []byte) error {
	var res PictureSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
