// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StockItemChannelSkuResponse stock item channel sku response
//
// swagger:model StockItemChannelSkuResponse
type StockItemChannelSkuResponse struct {

	// channel skus
	ChannelSkus []*StockItemChannelSKU `json:"ChannelSkus"`

	// stock item Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	StockItemID strfmt.UUID `json:"StockItemId,omitempty"`
}

// Validate validates this stock item channel sku response
func (m *StockItemChannelSkuResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChannelSkus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStockItemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StockItemChannelSkuResponse) validateChannelSkus(formats strfmt.Registry) error {
	if swag.IsZero(m.ChannelSkus) { // not required
		return nil
	}

	for i := 0; i < len(m.ChannelSkus); i++ {
		if swag.IsZero(m.ChannelSkus[i]) { // not required
			continue
		}

		if m.ChannelSkus[i] != nil {
			if err := m.ChannelSkus[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("ChannelSkus" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("ChannelSkus" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *StockItemChannelSkuResponse) validateStockItemID(formats strfmt.Registry) error {
	if swag.IsZero(m.StockItemID) { // not required
		return nil
	}

	if err := validate.FormatOf("StockItemId", "body", "uuid", m.StockItemID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this stock item channel sku response based on the context it is used
func (m *StockItemChannelSkuResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChannelSkus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StockItemChannelSkuResponse) contextValidateChannelSkus(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ChannelSkus); i++ {

		if m.ChannelSkus[i] != nil {

			if swag.IsZero(m.ChannelSkus[i]) { // not required
				return nil
			}

			if err := m.ChannelSkus[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("ChannelSkus" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("ChannelSkus" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *StockItemChannelSkuResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StockItemChannelSkuResponse) UnmarshalBinary(b []byte) error {
	var res StockItemChannelSkuResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
