// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StockItemExtendedProperty stock item extended property
//
// swagger:model StockItemExtendedProperty
type StockItemExtendedProperty struct {

	// Property type
	PropertyType string `json:"PropertyType,omitempty"`

	// Property value
	PropertyValue string `json:"PropertyValue,omitempty"`

	// Property name
	ProperyName string `json:"ProperyName,omitempty"`

	// Stock Item ID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	FkStockItemID strfmt.UUID `json:"fkStockItemId,omitempty"`

	// Record row ID (generate random)
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	PkRowID strfmt.UUID `json:"pkRowId,omitempty"`
}

// Validate validates this stock item extended property
func (m *StockItemExtendedProperty) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFkStockItemID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePkRowID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StockItemExtendedProperty) validateFkStockItemID(formats strfmt.Registry) error {
	if swag.IsZero(m.FkStockItemID) { // not required
		return nil
	}

	if err := validate.FormatOf("fkStockItemId", "body", "uuid", m.FkStockItemID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *StockItemExtendedProperty) validatePkRowID(formats strfmt.Registry) error {
	if swag.IsZero(m.PkRowID) { // not required
		return nil
	}

	if err := validate.FormatOf("pkRowId", "body", "uuid", m.PkRowID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this stock item extended property based on context it is used
func (m *StockItemExtendedProperty) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StockItemExtendedProperty) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StockItemExtendedProperty) UnmarshalBinary(b []byte) error {
	var res StockItemExtendedProperty
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
