// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateBatchDetailsRequest update batch details request
//
// swagger:model UpdateBatchDetailsRequest
type UpdateBatchDetailsRequest struct {

	// batch number scan required
	BatchNumberScanRequired bool `json:"BatchNumberScanRequired,omitempty"`

	// inventory tracking type
	InventoryTrackingType int32 `json:"InventoryTrackingType,omitempty"`

	// reset batch dates
	ResetBatchDates bool `json:"ResetBatchDates,omitempty"`

	// stock item Id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	StockItemID strfmt.UUID `json:"StockItemId,omitempty"`
}

// Validate validates this update batch details request
func (m *UpdateBatchDetailsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStockItemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateBatchDetailsRequest) validateStockItemID(formats strfmt.Registry) error {
	if swag.IsZero(m.StockItemID) { // not required
		return nil
	}

	if err := validate.FormatOf("StockItemId", "body", "uuid", m.StockItemID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update batch details request based on context it is used
func (m *UpdateBatchDetailsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateBatchDetailsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateBatchDetailsRequest) UnmarshalBinary(b []byte) error {
	var res UpdateBatchDetailsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
