// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChannelOrderNote channel order note
//
// swagger:model ChannelOrderNote
type ChannelOrderNote struct {

	// Declares if the note is an internal note
	Internal bool `json:"Internal,omitempty"`

	// Order Note
	Note string `json:"Note,omitempty"`

	// Creation Date of the note
	// Format: date-time
	NoteEntryDate strfmt.DateTime `json:"NoteEntryDate,omitempty"`

	// User who added the note
	NoteUserName string `json:"NoteUserName,omitempty"`
}

// Validate validates this channel order note
func (m *ChannelOrderNote) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNoteEntryDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChannelOrderNote) validateNoteEntryDate(formats strfmt.Registry) error {
	if swag.IsZero(m.NoteEntryDate) { // not required
		return nil
	}

	if err := validate.FormatOf("NoteEntryDate", "body", "date-time", m.NoteEntryDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this channel order note based on context it is used
func (m *ChannelOrderNote) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelOrderNote) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelOrderNote) UnmarshalBinary(b []byte) error {
	var res ChannelOrderNote
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
