// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChannelOrderExtendedProperty channel order extended property
//
// swagger:model ChannelOrderExtendedProperty
type ChannelOrderExtendedProperty struct {

	// Extended property name
	Name string `json:"Name,omitempty"`

	// Extended property type
	Type string `json:"Type,omitempty"`

	// Extended property value
	Value string `json:"Value,omitempty"`
}

// Validate validates this channel order extended property
func (m *ChannelOrderExtendedProperty) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this channel order extended property based on context it is used
func (m *ChannelOrderExtendedProperty) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelOrderExtendedProperty) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelOrderExtendedProperty) UnmarshalBinary(b []byte) error {
	var res ChannelOrderExtendedProperty
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
