// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSerialisedValuesForOrderItemsRequest create serialised values for order items request
//
// swagger:model CreateSerialisedValuesForOrderItemsRequest
type CreateSerialisedValuesForOrderItemsRequest struct {

	// order item serial data
	OrderItemSerialData []*OrderItemSerialModel `json:"OrderItemSerialData"`
}

// Validate validates this create serialised values for order items request
func (m *CreateSerialisedValuesForOrderItemsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderItemSerialData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSerialisedValuesForOrderItemsRequest) validateOrderItemSerialData(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderItemSerialData) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderItemSerialData); i++ {
		if swag.IsZero(m.OrderItemSerialData[i]) { // not required
			continue
		}

		if m.OrderItemSerialData[i] != nil {
			if err := m.OrderItemSerialData[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("OrderItemSerialData" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("OrderItemSerialData" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this create serialised values for order items request based on the context it is used
func (m *CreateSerialisedValuesForOrderItemsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrderItemSerialData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSerialisedValuesForOrderItemsRequest) contextValidateOrderItemSerialData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.OrderItemSerialData); i++ {

		if m.OrderItemSerialData[i] != nil {

			if swag.IsZero(m.OrderItemSerialData[i]) { // not required
				return nil
			}

			if err := m.OrderItemSerialData[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("OrderItemSerialData" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("OrderItemSerialData" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateSerialisedValuesForOrderItemsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSerialisedValuesForOrderItemsRequest) UnmarshalBinary(b []byte) error {
	var res CreateSerialisedValuesForOrderItemsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
