// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetOrderAuditTrailsByIdsResponse get order audit trails by ids response
//
// swagger:model GetOrderAuditTrailsByIdsResponse
type GetOrderAuditTrailsByIdsResponse struct {

	// audit trails
	AuditTrails []*OrderAuditTrailExtended `json:"AuditTrails"`
}

// Validate validates this get order audit trails by ids response
func (m *GetOrderAuditTrailsByIdsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuditTrails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetOrderAuditTrailsByIdsResponse) validateAuditTrails(formats strfmt.Registry) error {
	if swag.IsZero(m.AuditTrails) { // not required
		return nil
	}

	for i := 0; i < len(m.AuditTrails); i++ {
		if swag.IsZero(m.AuditTrails[i]) { // not required
			continue
		}

		if m.AuditTrails[i] != nil {
			if err := m.AuditTrails[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("AuditTrails" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("AuditTrails" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get order audit trails by ids response based on the context it is used
func (m *GetOrderAuditTrailsByIdsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuditTrails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetOrderAuditTrailsByIdsResponse) contextValidateAuditTrails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AuditTrails); i++ {

		if m.AuditTrails[i] != nil {

			if swag.IsZero(m.AuditTrails[i]) { // not required
				return nil
			}

			if err := m.AuditTrails[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("AuditTrails" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("AuditTrails" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetOrderAuditTrailsByIdsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetOrderAuditTrailsByIdsResponse) UnmarshalBinary(b []byte) error {
	var res GetOrderAuditTrailsByIdsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
