// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetOrderAuditTrailsByIdsRequest get order audit trails by ids request
//
// swagger:model GetOrderAuditTrailsByIdsRequest
type GetOrderAuditTrailsByIdsRequest struct {

	// List of order ids
	OrderIds []strfmt.UUID `json:"OrderIds"`
}

// Validate validates this get order audit trails by ids request
func (m *GetOrderAuditTrailsByIdsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetOrderAuditTrailsByIdsRequest) validateOrderIds(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderIds) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderIds); i++ {

		if err := validate.FormatOf("OrderIds"+"."+strconv.Itoa(i), "body", "uuid", m.OrderIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this get order audit trails by ids request based on context it is used
func (m *GetOrderAuditTrailsByIdsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetOrderAuditTrailsByIdsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetOrderAuditTrailsByIdsRequest) UnmarshalBinary(b []byte) error {
	var res GetOrderAuditTrailsByIdsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
