// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetOrderItemBatchesByOrderIdsResponse get order item batches by order ids response
//
// swagger:model GetOrderItemBatchesByOrderIdsResponse
type GetOrderItemBatchesByOrderIdsResponse struct {

	// order batches
	OrderBatches []*OrderItemBatchExtended `json:"OrderBatches"`
}

// Validate validates this get order item batches by order ids response
func (m *GetOrderItemBatchesByOrderIdsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderBatches(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetOrderItemBatchesByOrderIdsResponse) validateOrderBatches(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderBatches) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderBatches); i++ {
		if swag.IsZero(m.OrderBatches[i]) { // not required
			continue
		}

		if m.OrderBatches[i] != nil {
			if err := m.OrderBatches[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("OrderBatches" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("OrderBatches" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get order item batches by order ids response based on the context it is used
func (m *GetOrderItemBatchesByOrderIdsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrderBatches(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetOrderItemBatchesByOrderIdsResponse) contextValidateOrderBatches(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.OrderBatches); i++ {

		if m.OrderBatches[i] != nil {

			if swag.IsZero(m.OrderBatches[i]) { // not required
				return nil
			}

			if err := m.OrderBatches[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("OrderBatches" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("OrderBatches" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetOrderItemBatchesByOrderIdsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetOrderItemBatchesByOrderIdsResponse) UnmarshalBinary(b []byte) error {
	var res GetOrderItemBatchesByOrderIdsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
