// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KeyValuePairGUIDString key value pair Guid string
//
// swagger:model KeyValuePair_Guid_String
type KeyValuePairGUIDString struct {

	// key
	// Example: 00000000-0000-0000-0000-000000000000
	// Read Only: true
	// Format: uuid
	Key strfmt.UUID `json:"Key,omitempty"`

	// value
	// Read Only: true
	Value string `json:"Value,omitempty"`
}

// Validate validates this key value pair Guid string
func (m *KeyValuePairGUIDString) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeyValuePairGUIDString) validateKey(formats strfmt.Registry) error {
	if swag.IsZero(m.Key) { // not required
		return nil
	}

	if err := validate.FormatOf("Key", "body", "uuid", m.Key.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this key value pair Guid string based on the context it is used
func (m *KeyValuePairGUIDString) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeyValuePairGUIDString) contextValidateKey(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "Key", "body", m.Key); err != nil {
		return err
	}

	return nil
}

func (m *KeyValuePairGUIDString) contextValidateValue(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "Value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *KeyValuePairGUIDString) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KeyValuePairGUIDString) UnmarshalBinary(b []byte) error {
	var res KeyValuePairGUIDString
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
