// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersGetOpenOrdersByItemBarcodeRequest orders get open orders by item barcode request
//
// swagger:model Orders_GetOpenOrdersByItemBarcodeRequest
type OrdersGetOpenOrdersByItemBarcodeRequest struct {

	// Filters to apply
	Filters *FieldsFilter `json:"filters,omitempty"`

	// User location
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	LocationID strfmt.UUID `json:"locationId,omitempty"`

	// Item barcode
	ProductBarcode string `json:"productBarcode,omitempty"`
}

// Validate validates this orders get open orders by item barcode request
func (m *OrdersGetOpenOrdersByItemBarcodeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocationID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersGetOpenOrdersByItemBarcodeRequest) validateFilters(formats strfmt.Registry) error {
	if swag.IsZero(m.Filters) { // not required
		return nil
	}

	if m.Filters != nil {
		if err := m.Filters.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("filters")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("filters")
			}

			return err
		}
	}

	return nil
}

func (m *OrdersGetOpenOrdersByItemBarcodeRequest) validateLocationID(formats strfmt.Registry) error {
	if swag.IsZero(m.LocationID) { // not required
		return nil
	}

	if err := validate.FormatOf("locationId", "body", "uuid", m.LocationID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this orders get open orders by item barcode request based on the context it is used
func (m *OrdersGetOpenOrdersByItemBarcodeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFilters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersGetOpenOrdersByItemBarcodeRequest) contextValidateFilters(ctx context.Context, formats strfmt.Registry) error {

	if m.Filters != nil {

		if swag.IsZero(m.Filters) { // not required
			return nil
		}

		if err := m.Filters.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("filters")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("filters")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrdersGetOpenOrdersByItemBarcodeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersGetOpenOrdersByItemBarcodeRequest) UnmarshalBinary(b []byte) error {
	var res OrdersGetOpenOrdersByItemBarcodeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
