// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersSetExtendedPropertiesRequest orders set extended properties request
//
// swagger:model Orders_SetExtendedPropertiesRequest
type OrdersSetExtendedPropertiesRequest struct {

	// Extended property information
	ExtendedProperties []*ExtendedProperty `json:"extendedProperties"`

	// Order id (pkOrderID)
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	OrderID strfmt.UUID `json:"orderId,omitempty"`
}

// Validate validates this orders set extended properties request
func (m *OrdersSetExtendedPropertiesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExtendedProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersSetExtendedPropertiesRequest) validateExtendedProperties(formats strfmt.Registry) error {
	if swag.IsZero(m.ExtendedProperties) { // not required
		return nil
	}

	for i := 0; i < len(m.ExtendedProperties); i++ {
		if swag.IsZero(m.ExtendedProperties[i]) { // not required
			continue
		}

		if m.ExtendedProperties[i] != nil {
			if err := m.ExtendedProperties[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("extendedProperties" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("extendedProperties" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *OrdersSetExtendedPropertiesRequest) validateOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("orderId", "body", "uuid", m.OrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this orders set extended properties request based on the context it is used
func (m *OrdersSetExtendedPropertiesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExtendedProperties(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersSetExtendedPropertiesRequest) contextValidateExtendedProperties(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ExtendedProperties); i++ {

		if m.ExtendedProperties[i] != nil {

			if swag.IsZero(m.ExtendedProperties[i]) { // not required
				return nil
			}

			if err := m.ExtendedProperties[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("extendedProperties" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("extendedProperties" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrdersSetExtendedPropertiesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersSetExtendedPropertiesRequest) UnmarshalBinary(b []byte) error {
	var res OrdersSetExtendedPropertiesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
