// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersChangeStatusRequest orders change status request
//
// swagger:model Orders_ChangeStatusRequest
type OrdersChangeStatusRequest struct {

	// Order id's
	OrderIds []strfmt.UUID `json:"orderIds"`

	// New status
	Status int32 `json:"status,omitempty"`
}

// Validate validates this orders change status request
func (m *OrdersChangeStatusRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersChangeStatusRequest) validateOrderIds(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderIds) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderIds); i++ {

		if err := validate.FormatOf("orderIds"+"."+strconv.Itoa(i), "body", "uuid", m.OrderIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this orders change status request based on context it is used
func (m *OrdersChangeStatusRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrdersChangeStatusRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersChangeStatusRequest) UnmarshalBinary(b []byte) error {
	var res OrdersChangeStatusRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
