// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderFolder order folder
//
// swagger:model OrderFolder
type OrderFolder struct {

	// Folder name
	FolderName string `json:"FolderName,omitempty"`

	// Folder ID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	PkFolderID strfmt.UUID `json:"pkFolderId,omitempty"`
}

// Validate validates this order folder
func (m *OrderFolder) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePkFolderID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderFolder) validatePkFolderID(formats strfmt.Registry) error {
	if swag.IsZero(m.PkFolderID) { // not required
		return nil
	}

	if err := validate.FormatOf("pkFolderId", "body", "uuid", m.PkFolderID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this order folder based on context it is used
func (m *OrderFolder) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderFolder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderFolder) UnmarshalBinary(b []byte) error {
	var res OrderFolder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
