// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersSetOrderPackagingSplitRequest orders set order packaging split request
//
// swagger:model Orders_SetOrderPackagingSplitRequest
type OrdersSetOrderPackagingSplitRequest struct {

	// Order id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	OrderID strfmt.UUID `json:"orderId,omitempty"`

	// Order split
	PackagingSplit []*OrderPackagingSplit `json:"packagingSplit"`
}

// Validate validates this orders set order packaging split request
func (m *OrdersSetOrderPackagingSplitRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePackagingSplit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersSetOrderPackagingSplitRequest) validateOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("orderId", "body", "uuid", m.OrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OrdersSetOrderPackagingSplitRequest) validatePackagingSplit(formats strfmt.Registry) error {
	if swag.IsZero(m.PackagingSplit) { // not required
		return nil
	}

	for i := 0; i < len(m.PackagingSplit); i++ {
		if swag.IsZero(m.PackagingSplit[i]) { // not required
			continue
		}

		if m.PackagingSplit[i] != nil {
			if err := m.PackagingSplit[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("packagingSplit" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("packagingSplit" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this orders set order packaging split request based on the context it is used
func (m *OrdersSetOrderPackagingSplitRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePackagingSplit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersSetOrderPackagingSplitRequest) contextValidatePackagingSplit(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PackagingSplit); i++ {

		if m.PackagingSplit[i] != nil {

			if swag.IsZero(m.PackagingSplit[i]) { // not required
				return nil
			}

			if err := m.PackagingSplit[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("packagingSplit" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("packagingSplit" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrdersSetOrderPackagingSplitRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersSetOrderPackagingSplitRequest) UnmarshalBinary(b []byte) error {
	var res OrdersSetOrderPackagingSplitRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
