// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest orders get all available order item batchs by order Id request
//
// swagger:model Orders_GetAllAvailableOrderItemBatchsByOrderIdRequest
type OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest struct {

	// Made up of pkOrderId
	Parameters *AvailableOrderItemBatchsInfo `json:"parameters,omitempty"`
}

// Validate validates this orders get all available order item batchs by order Id request
func (m *OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest) validateParameters(formats strfmt.Registry) error {
	if swag.IsZero(m.Parameters) { // not required
		return nil
	}

	if m.Parameters != nil {
		if err := m.Parameters.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("parameters")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("parameters")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this orders get all available order item batchs by order Id request based on the context it is used
func (m *OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParameters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest) contextValidateParameters(ctx context.Context, formats strfmt.Registry) error {

	if m.Parameters != nil {

		if swag.IsZero(m.Parameters) { // not required
			return nil
		}

		if err := m.Parameters.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("parameters")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("parameters")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest) UnmarshalBinary(b []byte) error {
	var res OrdersGetAllAvailableOrderItemBatchsByOrderIDRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
