// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrdersSetAvailableFoldersRequest orders set available folders request
//
// swagger:model Orders_SetAvailableFoldersRequest
type OrdersSetAvailableFoldersRequest struct {

	// folders list
	Folders []*OrderFolder `json:"folders"`
}

// Validate validates this orders set available folders request
func (m *OrdersSetAvailableFoldersRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFolders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersSetAvailableFoldersRequest) validateFolders(formats strfmt.Registry) error {
	if swag.IsZero(m.Folders) { // not required
		return nil
	}

	for i := 0; i < len(m.Folders); i++ {
		if swag.IsZero(m.Folders[i]) { // not required
			continue
		}

		if m.Folders[i] != nil {
			if err := m.Folders[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("folders" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("folders" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this orders set available folders request based on the context it is used
func (m *OrdersSetAvailableFoldersRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFolders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersSetAvailableFoldersRequest) contextValidateFolders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Folders); i++ {

		if m.Folders[i] != nil {

			if swag.IsZero(m.Folders[i]) { // not required
				return nil
			}

			if err := m.Folders[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("folders" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("folders" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrdersSetAvailableFoldersRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersSetAvailableFoldersRequest) UnmarshalBinary(b []byte) error {
	var res OrdersSetAvailableFoldersRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
