// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersGetOrdersByIDRequest orders get orders by Id request
//
// swagger:model Orders_GetOrdersByIdRequest
type OrdersGetOrdersByIDRequest struct {

	// List of order ids (pkOrderId)
	PkOrderIds []strfmt.UUID `json:"pkOrderIds"`
}

// Validate validates this orders get orders by Id request
func (m *OrdersGetOrdersByIDRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePkOrderIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersGetOrdersByIDRequest) validatePkOrderIds(formats strfmt.Registry) error {
	if swag.IsZero(m.PkOrderIds) { // not required
		return nil
	}

	for i := 0; i < len(m.PkOrderIds); i++ {

		if err := validate.FormatOf("pkOrderIds"+"."+strconv.Itoa(i), "body", "uuid", m.PkOrderIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this orders get orders by Id request based on context it is used
func (m *OrdersGetOrdersByIDRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrdersGetOrdersByIDRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersGetOrdersByIDRequest) UnmarshalBinary(b []byte) error {
	var res OrdersGetOrdersByIDRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
