// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderNoteType order note type
//
// swagger:model OrderNoteType
type OrderNoteType struct {

	// note type
	NoteType string `json:"NoteType,omitempty"`

	// note type Id
	NoteTypeID int32 `json:"NoteTypeId,omitempty"`
}

// Validate validates this order note type
func (m *OrderNoteType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this order note type based on context it is used
func (m *OrderNoteType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderNoteType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderNoteType) UnmarshalBinary(b []byte) error {
	var res OrderNoteType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
