// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderRelation order relation
//
// swagger:model OrderRelation
type OrderRelation struct {

	// Child order ID
	Child int32 `json:"Child,omitempty"`

	// Child order GUID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	ChildOrderID strfmt.UUID `json:"ChildOrderId,omitempty"`

	// Parent order ID
	Parent int32 `json:"Parent,omitempty"`

	// Parent order GUID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	ParentOrderID strfmt.UUID `json:"ParentOrderId,omitempty"`

	// Relation type
	Type string `json:"Type,omitempty"`
}

// Validate validates this order relation
func (m *OrderRelation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChildOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentOrderID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderRelation) validateChildOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.ChildOrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("ChildOrderId", "body", "uuid", m.ChildOrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OrderRelation) validateParentOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.ParentOrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("ParentOrderId", "body", "uuid", m.ParentOrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this order relation based on context it is used
func (m *OrderRelation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderRelation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderRelation) UnmarshalBinary(b []byte) error {
	var res OrderRelation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
