// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderAuditTrail order audit trail
//
// swagger:model OrderAuditTrail
type OrderAuditTrail struct {

	// Date and time when audit record was added
	// Format: date-time
	Date strfmt.DateTime `json:"Date,omitempty"`

	// Actual audit trail note
	Note string `json:"Note,omitempty"`

	// Audit trail record tag
	Tag string `json:"Tag,omitempty"`

	// Note type
	Type string `json:"Type,omitempty"`

	// Note type description
	TypeDescription string `json:"TypeDescription,omitempty"`

	// User who left an audit trail record
	User string `json:"User,omitempty"`

	// Note type ID
	FkOrderHistoryTypeID string `json:"fkOrderHistoryTypeId,omitempty"`
}

// Validate validates this order audit trail
func (m *OrderAuditTrail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderAuditTrail) validateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.Date) { // not required
		return nil
	}

	if err := validate.FormatOf("Date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this order audit trail based on context it is used
func (m *OrderAuditTrail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderAuditTrail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderAuditTrail) UnmarshalBinary(b []byte) error {
	var res OrderAuditTrail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
