// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersCreateNewItemAndLinkRequest orders create new item and link request
//
// swagger:model Orders_CreateNewItemAndLinkRequest
type OrdersCreateNewItemAndLinkRequest struct {

	// Channel SKU
	ChannelSKU string `json:"channelSKU,omitempty"`

	// Initial quantity once the inventory item has been created
	InitialQuantity int32 `json:"initialQuantity,omitempty"`

	// Title
	ItemTitle string `json:"itemTitle,omitempty"`

	// User location
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	LocationID strfmt.UUID `json:"locationId,omitempty"`

	// Stock item id
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	PkStockItemID strfmt.UUID `json:"pkStockItemId,omitempty"`

	// Source
	Source string `json:"source,omitempty"`

	// Subsource
	SubSource string `json:"subSource,omitempty"`
}

// Validate validates this orders create new item and link request
func (m *OrdersCreateNewItemAndLinkRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePkStockItemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersCreateNewItemAndLinkRequest) validateLocationID(formats strfmt.Registry) error {
	if swag.IsZero(m.LocationID) { // not required
		return nil
	}

	if err := validate.FormatOf("locationId", "body", "uuid", m.LocationID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OrdersCreateNewItemAndLinkRequest) validatePkStockItemID(formats strfmt.Registry) error {
	if swag.IsZero(m.PkStockItemID) { // not required
		return nil
	}

	if err := validate.FormatOf("pkStockItemId", "body", "uuid", m.PkStockItemID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this orders create new item and link request based on context it is used
func (m *OrdersCreateNewItemAndLinkRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrdersCreateNewItemAndLinkRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersCreateNewItemAndLinkRequest) UnmarshalBinary(b []byte) error {
	var res OrdersCreateNewItemAndLinkRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
