// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersGetAllOpenOrdersBetweenIndexRequest orders get all open orders between index request
//
// swagger:model Orders_GetAllOpenOrdersBetweenIndexRequest
type OrdersGetAllOpenOrdersBetweenIndexRequest struct {

	// Additional filter
	AdditionalFilter string `json:"additionalFilter,omitempty"`

	// Filters to apply
	Filters *FieldsFilter `json:"filters,omitempty"`

	// From index
	FromIndex int32 `json:"fromIndex,omitempty"`

	// Location to get the orders for
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	FulfilmentCenter strfmt.UUID `json:"fulfilmentCenter,omitempty"`

	// Sorting to apply
	Sorting []*FieldSorting `json:"sorting"`

	// To index
	ToIndex int32 `json:"toIndex,omitempty"`
}

// Validate validates this orders get all open orders between index request
func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFulfilmentCenter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSorting(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) validateFilters(formats strfmt.Registry) error {
	if swag.IsZero(m.Filters) { // not required
		return nil
	}

	if m.Filters != nil {
		if err := m.Filters.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("filters")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("filters")
			}

			return err
		}
	}

	return nil
}

func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) validateFulfilmentCenter(formats strfmt.Registry) error {
	if swag.IsZero(m.FulfilmentCenter) { // not required
		return nil
	}

	if err := validate.FormatOf("fulfilmentCenter", "body", "uuid", m.FulfilmentCenter.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) validateSorting(formats strfmt.Registry) error {
	if swag.IsZero(m.Sorting) { // not required
		return nil
	}

	for i := 0; i < len(m.Sorting); i++ {
		if swag.IsZero(m.Sorting[i]) { // not required
			continue
		}

		if m.Sorting[i] != nil {
			if err := m.Sorting[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("sorting" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("sorting" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this orders get all open orders between index request based on the context it is used
func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFilters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSorting(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) contextValidateFilters(ctx context.Context, formats strfmt.Registry) error {

	if m.Filters != nil {

		if swag.IsZero(m.Filters) { // not required
			return nil
		}

		if err := m.Filters.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("filters")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("filters")
			}

			return err
		}
	}

	return nil
}

func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) contextValidateSorting(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Sorting); i++ {

		if m.Sorting[i] != nil {

			if swag.IsZero(m.Sorting[i]) { // not required
				return nil
			}

			if err := m.Sorting[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("sorting" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("sorting" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersGetAllOpenOrdersBetweenIndexRequest) UnmarshalBinary(b []byte) error {
	var res OrdersGetAllOpenOrdersBetweenIndexRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
