// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrdersCreateNewOrderRequest orders create new order request
//
// swagger:model Orders_CreateNewOrderRequest
type OrdersCreateNewOrderRequest struct {

	// create as draft
	CreateAsDraft bool `json:"createAsDraft,omitempty"`

	// Fulfilment center to be associated
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	FulfilmentCenter strfmt.UUID `json:"fulfilmentCenter,omitempty"`
}

// Validate validates this orders create new order request
func (m *OrdersCreateNewOrderRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFulfilmentCenter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrdersCreateNewOrderRequest) validateFulfilmentCenter(formats strfmt.Registry) error {
	if swag.IsZero(m.FulfilmentCenter) { // not required
		return nil
	}

	if err := validate.FormatOf("fulfilmentCenter", "body", "uuid", m.FulfilmentCenter.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this orders create new order request based on context it is used
func (m *OrdersCreateNewOrderRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrdersCreateNewOrderRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersCreateNewOrderRequest) UnmarshalBinary(b []byte) error {
	var res OrdersCreateNewOrderRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
