// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetPickListPrintedRequest set pick list printed request
//
// swagger:model SetPickListPrintedRequest
type SetPickListPrintedRequest struct {

	// If stock batches needs to be assigned this defines how they should be assigned
	// Enum: ["ALL","AUTO_ONLY","UNASSIGNED_ONLY"]
	BatchAssignmentMode string `json:"BatchAssignmentMode,omitempty"`

	// A list of orders that should be assigned the IsPrinted value
	OrderIds []strfmt.UUID `json:"OrderIds"`
}

// Validate validates this set pick list printed request
func (m *SetPickListPrintedRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBatchAssignmentMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var setPickListPrintedRequestTypeBatchAssignmentModePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ALL","AUTO_ONLY","UNASSIGNED_ONLY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		setPickListPrintedRequestTypeBatchAssignmentModePropEnum = append(setPickListPrintedRequestTypeBatchAssignmentModePropEnum, v)
	}
}

const (

	// SetPickListPrintedRequestBatchAssignmentModeALL captures enum value "ALL"
	SetPickListPrintedRequestBatchAssignmentModeALL string = "ALL"

	// SetPickListPrintedRequestBatchAssignmentModeAUTOONLY captures enum value "AUTO_ONLY"
	SetPickListPrintedRequestBatchAssignmentModeAUTOONLY string = "AUTO_ONLY"

	// SetPickListPrintedRequestBatchAssignmentModeUNASSIGNEDONLY captures enum value "UNASSIGNED_ONLY"
	SetPickListPrintedRequestBatchAssignmentModeUNASSIGNEDONLY string = "UNASSIGNED_ONLY"
)

// prop value enum
func (m *SetPickListPrintedRequest) validateBatchAssignmentModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, setPickListPrintedRequestTypeBatchAssignmentModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SetPickListPrintedRequest) validateBatchAssignmentMode(formats strfmt.Registry) error {
	if swag.IsZero(m.BatchAssignmentMode) { // not required
		return nil
	}

	// value enum
	if err := m.validateBatchAssignmentModeEnum("BatchAssignmentMode", "body", m.BatchAssignmentMode); err != nil {
		return err
	}

	return nil
}

func (m *SetPickListPrintedRequest) validateOrderIds(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderIds) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderIds); i++ {

		if err := validate.FormatOf("OrderIds"+"."+strconv.Itoa(i), "body", "uuid", m.OrderIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this set pick list printed request based on context it is used
func (m *SetPickListPrintedRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetPickListPrintedRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetPickListPrintedRequest) UnmarshalBinary(b []byte) error {
	var res SetPickListPrintedRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
