// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExistingRefundTotal existing refund total
//
// swagger:model ExistingRefundTotal
type ExistingRefundTotal struct {

	// Amount refunded
	Amount float64 `json:"Amount,omitempty"`

	// Refundable amount
	// Read Only: true
	Refundable float64 `json:"Refundable,omitempty"`

	// Total order charge
	TotalCharge float64 `json:"TotalCharge,omitempty"`
}

// Validate validates this existing refund total
func (m *ExistingRefundTotal) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this existing refund total based on the context it is used
func (m *ExistingRefundTotal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRefundable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExistingRefundTotal) contextValidateRefundable(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "Refundable", "body", m.Refundable); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExistingRefundTotal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExistingRefundTotal) UnmarshalBinary(b []byte) error {
	var res ExistingRefundTotal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
