// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProcessedOrdersIsRefundValidRequest processed orders is refund valid request
//
// swagger:model ProcessedOrders_IsRefundValidRequest
type ProcessedOrdersIsRefundValidRequest struct {

	// The id of the order to validate the refund with
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	PkOrderID strfmt.UUID `json:"pkOrderId,omitempty"`

	// The refund rows
	RefundItems []*RefundItem `json:"refundItems"`
}

// Validate validates this processed orders is refund valid request
func (m *ProcessedOrdersIsRefundValidRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePkOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefundItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessedOrdersIsRefundValidRequest) validatePkOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.PkOrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("pkOrderId", "body", "uuid", m.PkOrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ProcessedOrdersIsRefundValidRequest) validateRefundItems(formats strfmt.Registry) error {
	if swag.IsZero(m.RefundItems) { // not required
		return nil
	}

	for i := 0; i < len(m.RefundItems); i++ {
		if swag.IsZero(m.RefundItems[i]) { // not required
			continue
		}

		if m.RefundItems[i] != nil {
			if err := m.RefundItems[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("refundItems" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("refundItems" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this processed orders is refund valid request based on the context it is used
func (m *ProcessedOrdersIsRefundValidRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRefundItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessedOrdersIsRefundValidRequest) contextValidateRefundItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RefundItems); i++ {

		if m.RefundItems[i] != nil {

			if swag.IsZero(m.RefundItems[i]) { // not required
				return nil
			}

			if err := m.RefundItems[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("refundItems" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("refundItems" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProcessedOrdersIsRefundValidRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessedOrdersIsRefundValidRequest) UnmarshalBinary(b []byte) error {
	var res ProcessedOrdersIsRefundValidRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
