// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProcessedOrdersDeleteReturnCategoryRequest processed orders delete return category request
//
// swagger:model ProcessedOrders_DeleteReturnCategoryRequest
type ProcessedOrdersDeleteReturnCategoryRequest struct {

	// The id of the category to delete.
	PkItemID int32 `json:"pkItemId,omitempty"`
}

// Validate validates this processed orders delete return category request
func (m *ProcessedOrdersDeleteReturnCategoryRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this processed orders delete return category request based on context it is used
func (m *ProcessedOrdersDeleteReturnCategoryRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProcessedOrdersDeleteReturnCategoryRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessedOrdersDeleteReturnCategoryRequest) UnmarshalBinary(b []byte) error {
	var res ProcessedOrdersDeleteReturnCategoryRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
