// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProcessedOrderRelation processed order relation
//
// swagger:model ProcessedOrderRelation
type ProcessedOrderRelation struct {

	// Child order number
	ChildOrderID int32 `json:"ChildOrderId,omitempty"`

	// Child order ID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	ChildOrderPkOrderID strfmt.UUID `json:"ChildOrderPkOrderId,omitempty"`

	// Parent order number
	ParentOrderID int32 `json:"ParentOrderId,omitempty"`

	// Parent order ID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	ParentOrderPkOrderID strfmt.UUID `json:"ParentOrderPkOrderId,omitempty"`

	// Relation type
	RelationType string `json:"RelationType,omitempty"`
}

// Validate validates this processed order relation
func (m *ProcessedOrderRelation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChildOrderPkOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentOrderPkOrderID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessedOrderRelation) validateChildOrderPkOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.ChildOrderPkOrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("ChildOrderPkOrderId", "body", "uuid", m.ChildOrderPkOrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ProcessedOrderRelation) validateParentOrderPkOrderID(formats strfmt.Registry) error {
	if swag.IsZero(m.ParentOrderPkOrderID) { // not required
		return nil
	}

	if err := validate.FormatOf("ParentOrderPkOrderId", "body", "uuid", m.ParentOrderPkOrderID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this processed order relation based on context it is used
func (m *ProcessedOrderRelation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProcessedOrderRelation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessedOrderRelation) UnmarshalBinary(b []byte) error {
	var res ProcessedOrderRelation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
