// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TrackingURLResponseItem tracking URL response item
//
// swagger:model TrackingURLResponseItem
type TrackingURLResponseItem struct {

	// order Id
	OrderID int32 `json:"OrderId,omitempty"`

	// postal tracking number
	PostalTrackingNumber string `json:"PostalTrackingNumber,omitempty"`

	// postcode
	Postcode string `json:"Postcode,omitempty"`

	// tracking URL
	TrackingURL string `json:"TrackingURL,omitempty"`

	// vendor
	Vendor string `json:"Vendor,omitempty"`
}

// Validate validates this tracking URL response item
func (m *TrackingURLResponseItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tracking URL response item based on context it is used
func (m *TrackingURLResponseItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrackingURLResponseItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrackingURLResponseItem) UnmarshalBinary(b []byte) error {
	var res TrackingURLResponseItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
